### ISSUE TITLE
Add "upload pictures" to User Submissions

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm#912]

**Comment by scottwainstock** [comment]
https://www.pluralsight.com/guides/handling-file-upload-using-ruby-on-rails-5-api

Going with Base64 encoded.

**Comment by RyanTG** [comment]
I doubt this is helpful since I don't totally understand wassappening, but I wanted to state it just in case: We just need to capture the "metadata" of these user submissions, right? Like, "a photo was uploaded to Ground Kontrol by [username]". As far as I know, we don't need to send the actual jpg data. But maybe we do... I dunno.

**Comment by bpoore** [comment]
@RyanTG, I agree for on the user profile we can reference metadata about photo submissions. I'm not sure how the process of approving photos works or anything like that... does an uploaded photo count differently than updating a location for a user? Perhaps we can include a photo upload in the same way we handle any other location update, by generically adding that they've updated that location on their profile? 
<img width="357" alt="screen shot 2019-03-07 at 6 14 12 pm" src="https://user-images.githubusercontent.com/7720282/54002869-f1910b00-4104-11e9-8933-905e8a9de425.png">
Or is the idea to show received submissions because they have to wait for approval? 

As for https://github.com/bpoore/pbm-react/issues/112, we do need to have an approach to submit and receive images via the API, so we will need to work with jpg data.

**Comment by RyanTG** [comment]
https://github.com/pinballmap/pbm/commit/d29c924897cae71d2ae61d14d62acd1aad527495 https://github.com/pinballmap/pbm/commit/f6ae0e471d210051b02aea80c40f67936d7f31c5

related: https://github.com/pinballmap/pbm/issues/1585
